### PR TITLE
Allow products as well as entries, so this can help with sorting Craf…

### PR DESCRIPTION
**Pull request by bossanova808**
…t Commerce products, in particular it's useful for doing a holistic search of content and products, with integrated results sorted by score.

E.g.:

```
    {% set product_results = craft.commerce.products.search(query).order('score').limit(15) %}  
    {% set article_results = craft.entries.search(query).order('score').limit(15) %}
    {% set all_results = product_results|merge(article_results)|sortByField('searchScore', 'desc') %}
```

### CODE REVIEW

**Comment by dannynimmo** [comment]
@bossanova808 Your expression has a bug, the `or` is going to override the previous expressions.

**Comment by bossanova808** [comment]
There's brackets around it so it's `anding` the result of that or to the other two.  So I read it as

Not this:
`!(isset($content[0]) `

And this:
`&& is_object($content[0]) `

And (either an Entry or a Product)
`&& (get_class($content[0]) === 'Craft\EntryModel') or get_class($content[0]) === 'Craft\Commerce_ProductModel')`

I'm rusty on PHP so I may be getting precedence wrong or something - but looks ok to me?  Actually, that should probably be `||` in php right?  Although it seems they have the same precedence here: https://secure.php.net/manual/en/language.operators.precedence.php 

Anyway, will update, one sec

**Comment by bossanova808** [comment]
Is that clearer/better?  Feel free to do it your preferred way.  :) 
Both seem to work identically here as it happens.

**Comment by dannynimmo** [comment]
@bossanova808 In PHP `&&` will take precedence over `||`, so the issue is if any one of the first 3 expressions are `false`, PHP will then check the final expression which could cause a notice.

This is actually true:
`false && false && false || true`

What we want:
`true && true && (false || true)`

If you can modify your pull request for that then I can accept it.

**Comment by bossanova808** [comment]
but brackets force precedence over operator precedence I thought?  Do I have he brackets wrong?  I don't want to waste your time but I am not seeing it.

not (true && true && (true || false))
= not (true & true && true) 
= false, exception not raised as desired...

But in any case, I would think you could
`elseif(! (@get_class($content[0]) === 'Craft\EntryModel' || @get_class($content[0]) === 'Craft\Commerce_ProductModel'))`

Which reads better, no?  And will return false if either of those is true, and not raise the exception.

Sorry, I am feeling a bit dumb here.  Don't want to waste your time - if you right it as your desired way I'll check it out and learn from it.

**Comment by dannynimmo** [comment]
@bossanova808 I think you had the correct idea, maybe just a typo in your code. Anyway, I've committed your change with the typo fixed so feel free to look at the diff & compare to yours.

**Pull request closed without merging**
